### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by loustack17** [Leucothea/ShadowverseChineseLocal#14]
好的，那Source Code的部份可以借我研究參考嘛？
如有更動...可能還是希望你們允許...

**Comment by loustack17** [comment]
請問這套可以使用在mac上嘛？

**Comment by Asanatsu** [comment]
本项目已停止维护了，补丁由前组员Emiter继续维护，可以用在MAC上，如有兴趣可加QQ群620272693，咨询群主Emiter即可：https://jq.qq.com/?_wv=1027&k=5oY7PkL ，感谢一直以来的关注~
