### ISSUE TITLE
字体显示大小不一致的问题。

### ISSUE THREAD

**Issue by fuchanghao** [Leucothea/ShadowverseChineseLocal#7]
在繁体中文版的基础上(非日文/英文版)，打上此补丁时，会导致很多文字出现字体和字号不一的问题，无论是5.5版本还是最新源码的编译版都有这个问题。

**Comment by Asanatsu** [comment]
感谢反馈。下版计划为台版打系统字体补丁，可以解决这个问题。

**Comment by Asanatsu** [comment]
你好，很遗憾这边发现没有办法给PC台版打系统字体补丁，因为英文版是把繁体字体做到英文字体里了，不换字体的话没法解决，所以现在不推荐在台版基础上打汉化补丁哦，请谅解。
