### ISSUE TITLE
安装程序的图标显示问题

### ISSUE THREAD

**Issue by df32** [Leucothea/ShadowverseChineseLocal#8]
**问题：**
在“大图标”视图模式下，ShadowverseLangPatch.exe的图标显示为小图片且带有锯齿。
**建议：**
调整ico.ico包含以下帧：256x256, 32x32, 24x24, 16x16

或者也可以直接用[这个我修改的图标](https://pan.baidu.com/s/1qYPm1YW)  密码: jp2w

**Comment by Asanatsu** [comment]
您好，抱歉回复的有些晚。
现在的程序图标尺寸是128x128，之前有考虑过做成256x256或更大，但是有不少XP玩家反应，128尺寸以上的图标都无法正常显示。为了兼容XP老玩家，我们只好做成128尺寸，请理解_(:з」∠)_同样感谢您的反馈~
